### ISSUE TITLE
Resumable error: HTTP 416 Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by leefsmp** [Autodesk-Forge/forge.commandline-nodejs#3]
Getting "HTTP 416 Requested Range Not Satisfiable" when testing resumable upload

**Comment by cyrillef** [comment]
works fine for me, what did you try as command and what is the filesize. Chunks minimum is 2Mb, and minimum 2 pieces, so your file must be > 2Mb
my command to test was: node forge-cb.js resumable ~/_samples/ESL.rvt 4

**Comment by leefsmp** [comment]
Ok I was trying with a smaller file. It's not obvious than the file needs to be > 2MB, in the help files the example is uploading 15 bytes.

**Comment by leefsmp** [comment]
What is the recommended chunk size by the way?

**Comment by cyrillef** [comment]
The recommended chunk size is 5Mb, the minimum chunk size (excepted the last bit) is 2Mb
