### ISSUE TITLE
Getting this warning even after upgrade

### ISSUE THREAD

**Issue by asha23** [Autodesk-Forge/forge.commandline-nodejs#6]
`WARNING: The 'Forge Design Automation v2' API is deprecated in favor of the 'Forge Design Automation v3' API npm package (aka: npm install autodesk.forge.designautomation), please upgrade.`

**Comment by cyrillef** [comment]
Yes, this is correct - in index.js line #25, I put that message to tell people not to use this package for Design Automation API. This package uses the v2 API which is obsolete, you really need to move to v3.
I just added a way to turn it off and to display only when using v2. If you upgrade to 0.7.2, it should disappear automatically. If you are still using Design Automation v2, you need to add this line:
```
ForgeSdk.disable_dav2_deprecated_Warning(true);
```
